# More info around this file at https://www.git-town.com/configuration-file

[branches]
main = "master"
perennials = []
perennial-regex = ""

[create]
new-branch-type = ""
push-new-branches = false

[hosting]
dev-remote = "origin"
# forge-type = ""
# origin-hostname = ""

[ship]
delete-tracking-branch = false
strategy = "api"

[sync]
feature-strategy = "rebase"
perennial-strategy = "rebase"
prototype-strategy = "rebase"
push-hook = true
tags = true
upstream = false
