name: CI

on:
  pull_request:
    branches: [ '**' ]
  push:
    branches: [ "master" ]
    tags: [ "v*" ]

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  test:
    strategy:
      matrix:
        os:
          - name: ubuntu-latest
            command: ./mill
          - name: windows-latest
            command: mill.bat

    runs-on: ${{ matrix.os.name }}

    steps:
      - uses: actions/checkout@v3
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          jvm: temurin:17

      - name: Test
        run: |
          ${{ matrix.os.command }} --no-server --jobs 1 __.downloadMillTestVersion 
          ${{ matrix.os.command }} --no-server --jobs 0 _.test

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: always() # always run even if the previous step fails
        with:
          detailed_summary: true
          annotate_only: true
          report_paths: 'out/**/test-report.xml'

  publish:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v'))

    steps:
      - uses: actions/checkout@v3
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          jvm: adopt:8

      - name: Publish
        run: ${{ matrix.os.command }} --no-server --jobs 0 io.kipp.mill.ci.release.ReleaseModule/publishAll
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
